package duncan.atkinson.dataobjects;

import java.util.Objects;

public class ReceiptLine {
    private final String productDescription;
    private final CHF cost;
    private final CHF tax;
    private final CHF discountAmount;

    // ALL CODE BELOW HERE IS GENERATED BY IDE DO NOT MODIFY

    public ReceiptLine(String productDescription, CHF cost, CHF tax, CHF discountAmount) {
        this.productDescription = productDescription;
        this.cost = cost;
        this.tax = tax;
        this.discountAmount = discountAmount;
    }

    private ReceiptLine(Builder builder) {
        productDescription = builder.productDescription;
        cost = builder.cost;
        tax = builder.tax;
        discountAmount = builder.discountAmount;
    }

    public static Builder newBuilder(String productDescription, CHF cost, CHF tax, CHF discountAmount) {
        return new Builder(productDescription, cost, tax, discountAmount);
    }

    public static Builder newBuilder(ReceiptLine copy) {
        Builder builder = new Builder(copy.productDescription, copy.cost, copy.tax, copy.discountAmount);
        return builder;
    }

    public String getProductDescription() {
        return productDescription;
    }

    public CHF getCost() {
        return cost;
    }

    public CHF getTax() {
        return tax;
    }

    public CHF getDiscountAmount() {
        return discountAmount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ReceiptLine that = (ReceiptLine) o;
        return Objects.equals(productDescription, that.productDescription) &&
                Objects.equals(cost, that.cost) &&
                Objects.equals(tax, that.tax) &&
                Objects.equals(discountAmount, that.discountAmount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productDescription, cost, tax, discountAmount);
    }

    @Override
    public String toString() {
        return "ReceiptLine{" +
                "productDescription='" + productDescription + '\'' +
                ", cost=" + cost +
                ", tax=" + tax +
                ", discountAmount=" + discountAmount +
                '}';
    }


    public static final class Builder {
        private final String productDescription;
        private final CHF cost;
        private final CHF tax;
        private final CHF discountAmount;

        private Builder(String productDescription, CHF cost, CHF tax, CHF discountAmount) {
            this.productDescription = productDescription;
            this.cost = cost;
            this.tax = tax;
            this.discountAmount = discountAmount;
        }

        public ReceiptLine build() {
            return new ReceiptLine(this);
        }
    }
}
