package duncan.atkinson.dataobjects;

import java.util.Objects;

/**
 * TODO add tests for constructors
 */
public class ReceiptLine {
    private final String productDescription;
    private final CHF cost;
    private final CHF tax;// NOT NEEDED
    private final CHF discountAmount;
    private final String discountReason;

    public ReceiptLine(String productDescription, CHF cost, CHF tax, CHF discountAmount, String discountReason) {
        this.productDescription = productDescription;
        this.cost = cost;
        this.tax = tax;
        this.discountAmount = discountAmount;
        this.discountReason = discountReason;
    }

    public ReceiptLine(String productDescription, CHF cost, CHF tax) {
        this.productDescription = productDescription;
        this.cost = cost;
        this.tax = tax;
        this.discountAmount = null;
        this.discountReason = null;
    }

    // ALL CODE BELOW HERE IS GENERATED BY IDE DO NOT MODIFY


    public String getProductDescription() {
        return productDescription;
    }

    public CHF getCost() {
        return cost;
    }

    public CHF getTax() {
        return tax;
    }

    public CHF getDiscountAmount() {
        return discountAmount;
    }

    public String getDiscountReason() {
        return discountReason;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ReceiptLine that = (ReceiptLine) o;
        return Objects.equals(productDescription, that.productDescription) &&
                Objects.equals(cost, that.cost) &&
                Objects.equals(tax, that.tax) &&
                Objects.equals(discountAmount, that.discountAmount) &&
                Objects.equals(discountReason, that.discountReason);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productDescription, cost, tax, discountAmount, discountReason);
    }

    @Override
    public String toString() {
        return "ReceiptLine{" +
                "productDescription='" + productDescription + '\'' +
                ", cost=" + cost +
                ", tax=" + tax +
                ", discountAmount=" + discountAmount +
                ", discountReason='" + discountReason + '\'' +
                '}';
    }

    public boolean hasDiscount() {
        return discountAmount != null;
    }
}
