package duncan.atkinson.dataobjects;

import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Object to hold data receipt data
 */
public class Receipt {

    private List<ReceiptLine> lines;

    private final CHF totalCost;

    private CHF taxAmount;

    // ALL CODE BELOW HERE IS GENERATED BY IDE DO NOT MODIFY

    public Receipt(List<ReceiptLine> lines, CHF totalCost, CHF taxAmount) {
        this.lines = lines;
        this.totalCost = totalCost;
        this.taxAmount = taxAmount;
    }

    public List<ReceiptLine> getLines() {
        return Collections.unmodifiableList(lines);
    }

    public CHF getTaxAmount() {
        return taxAmount;
    }

    public CHF getTotalCost() {
        return totalCost;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Receipt receipt = (Receipt) o;
        return Objects.equals(lines, receipt.lines) &&
                Objects.equals(totalCost, receipt.totalCost) &&
                Objects.equals(taxAmount, receipt.taxAmount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(lines, totalCost, taxAmount);
    }

    @Override
    public String toString() {
        return "Receipt{" +
                "lines=" + lines +
                ", totalCost=" + totalCost +
                ", taxAmount=" + taxAmount +
                '}';
    }
}
